### ISSUE TITLE
Manually bring in styles into consuming app

### ISSUE THREAD

**Issue by alvincrespo** [EvicoreQpidHealth/qpid-ember-base#3]
As of right now, because themes are part of the addon, it is difficult to override themes. For example, if we implement #2  - we'll need to define themes in our app.scss - however _buttons.scss will not be compiled before the themes are defined. 

This essentially means we need to copy _buttons.scss and then override with themify again in our consuming app. 

To avoid this, files like _buttons.scss should be audited to have default styles without theming and then the consuming app should define the theme it wants.

**Comment by Nikash** [comment]
Fixed with #9.
